[project]
name = "aidev-ai-blueking"
version = "2.2.2b3"
description = "小鲸静态资源包"
readme = "readme.md"
requires-python = ">=3.11.9, <4"
dependencies = [
    "aidev-agent>=2.2.1rc290",
    "django>=4.2.28,<5.0",
]


[tool.pdm.build]
includes = ["aidev_ai_blueking"]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
