# Generated by Django 4.2.29 on 2026-06-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Write',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_id', models.CharField(max_length=255)),
                ('checkpoint_ns', models.CharField(default='', max_length=255)),
                ('checkpoint_id', models.CharField(max_length=255)),
                ('task_id', models.CharField(max_length=255)),
                ('task_path', models.TextField()),
                ('idx', models.IntegerField()),
                ('channel', models.TextField()),
                ('type', models.TextField(blank=True, null=True)),
                ('value', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['thread_id', 'checkpoint_ns', 'checkpoint_id'], name='aidev_bkplu_thread__a70092_idx'), models.Index(fields=['task_id', 'idx'], name='aidev_bkplu_task_id_a0954b_idx'), models.Index(fields=['created_at'], name='aidev_bkplu_created_a12e42_idx'), models.Index(fields=['updated_at'], name='aidev_bkplu_updated_c9e6ad_idx')],
            },
        ),
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_id', models.CharField(max_length=255)),
                ('checkpoint_ns', models.CharField(default='', max_length=255)),
                ('checkpoint_id', models.CharField(max_length=255)),
                ('parent_checkpoint_id', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('checkpoint', models.BinaryField()),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['thread_id', 'checkpoint_ns'], name='aidev_bkplu_thread__04b367_idx'), models.Index(fields=['checkpoint_id'], name='aidev_bkplu_checkpo_fe6512_idx'), models.Index(fields=['created_at'], name='aidev_bkplu_created_09c71a_idx'), models.Index(fields=['updated_at'], name='aidev_bkplu_updated_f2e9a3_idx')],
            },
        ),
    ]
