# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_id', models.CharField(max_length=255)),
                ('checkpoint_ns', models.CharField(default='', max_length=255)),
                ('checkpoint_id', models.CharField(max_length=255)),
                ('parent_checkpoint_id', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('checkpoint', models.BinaryField()),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Write',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_id', models.CharField(max_length=255)),
                ('checkpoint_ns', models.CharField(default='', max_length=255)),
                ('checkpoint_id', models.CharField(max_length=255)),
                ('task_id', models.CharField(max_length=255)),
                ('task_path', models.TextField()),
                ('idx', models.IntegerField()),
                ('channel', models.TextField()),
                ('type', models.TextField(blank=True, null=True)),
                ('value', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        # Checkpoint 表约束和索引
        migrations.AddConstraint(
            model_name='checkpoint',
            constraint=models.UniqueConstraint(fields=('thread_id', 'checkpoint_ns', 'checkpoint_id'), name='aidev_bkplugin_checkpoint_unique_checkpoint'),
        ),
        migrations.AddIndex(
            model_name='checkpoint',
            index=models.Index(fields=['thread_id', 'checkpoint_ns'], name='aidev_bkplu_thread__a2f8b8_idx'),
        ),
        migrations.AddIndex(
            model_name='checkpoint',
            index=models.Index(fields=['checkpoint_id'], name='aidev_bkplu_checkpo_c59e08_idx'),
        ),
        migrations.AddIndex(
            model_name='checkpoint',
            index=models.Index(fields=['created_at'], name='aidev_bkplu_created_c8f9a1_idx'),
        ),
        migrations.AddIndex(
            model_name='checkpoint',
            index=models.Index(fields=['updated_at'], name='aidev_bkplu_updated_cp_idx'),
        ),
        # Write 表约束和索引
        migrations.AddConstraint(
            model_name='write',
            constraint=models.UniqueConstraint(fields=('thread_id', 'checkpoint_ns', 'checkpoint_id', 'task_id', 'idx'), name='aidev_bkplugin_write_unique_write'),
        ),
        migrations.AddIndex(
            model_name='write',
            index=models.Index(fields=['thread_id', 'checkpoint_ns', 'checkpoint_id'], name='aidev_bkplu_thread__bb68b5_idx'),
        ),
        migrations.AddIndex(
            model_name='write',
            index=models.Index(fields=['task_id', 'idx'], name='aidev_bkplu_task_id_2f49a9_idx'),
        ),
        migrations.AddIndex(
            model_name='write',
            index=models.Index(fields=['created_at'], name='aidev_bkplu_created_w7e3b2_idx'),
        ),
        migrations.AddIndex(
            model_name='write',
            index=models.Index(fields=['updated_at'], name='aidev_bkplu_updated_wr_idx'),
        ),
    ]
